# Generated by Django 5.1.7 on 2025-04-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Troupeau',
            fields=[
                ('id_troupeau', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=50)),
                ('date_creation', models.DateField()),
                ('type', models.CharField(choices=[('laitier', 'Laitier'), ('viande', 'Viande'), ('mixte', 'Mixte')], max_length=10)),
            ],
        ),
    ]
