# Generated by Django 5.1.7 on 2025-04-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id_aliment', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom_aliment', models.CharField(max_length=100)),
                ('type_aliment', models.CharField(max_length=50)),
                ('stock_aliment', models.IntegerField()),
            ],
        ),
    ]
