# Generated by Django 5.1.7 on 2025-04-05 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_aliment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAliment',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('fournisseur_aliment', models.CharField(max_length=50)),
                ('stock_entree', models.IntegerField()),
                ('date_reception', models.DateField()),
                ('prix_aliment', models.IntegerField()),
                ('id_aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='my_app.aliment')),
            ],
        ),
    ]
