# Generated by Django 5.1.7 on 2025-04-10 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_stockaliment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ration',
            fields=[
                ('id_ration', models.AutoField(primary_key=True, serialize=False)),
                ('quantite_aliment', models.PositiveIntegerField()),
                ('date_ration', models.DateField()),
                ('id_aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rations', to='my_app.aliment')),
                ('id_troupeau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rations', to='my_app.troupeau')),
            ],
        ),
    ]
