# Generated by Django 5.1.7 on 2025-04-10 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_ration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id_individu', models.AutoField(primary_key=True, serialize=False)),
                ('numero_identification', models.CharField(max_length=50, unique=True)),
                ('sexe', models.CharField(choices=[('male', 'Mâle'), ('femelle', 'Femelle')], max_length=10)),
                ('date_naissance', models.DateField()),
                ('poids', models.DecimalField(decimal_places=2, max_digits=6)),
                ('etat_sante', models.CharField(choices=[('bon', 'Bon état'), ('malade', 'Malade'), ('traitement', 'En traitement')], max_length=10)),
                ('vaccins', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('id_troupeau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individus', to='my_app.troupeau')),
            ],
        ),
    ]
