# Generated by Django 5.1.7 on 2025-04-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_individu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('unite_mesure', models.CharField(choices=[('litres', 'Litres'), ('kg', 'Kilogrammes'), ('mga', 'MGA')], max_length=10)),
                ('date_expiration', models.DateField()),
            ],
        ),
    ]
