# Generated by Django 5.1.7 on 2025-04-10 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id_production', models.AutoField(primary_key=True, serialize=False)),
                ('date_production', models.DateField()),
                ('quantite', models.IntegerField()),
                ('poids_carcasse', models.DecimalField(decimal_places=2, max_digits=6)),
                ('id_individu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='my_app.individu')),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='my_app.produit')),
            ],
        ),
    ]
