# Generated by Django 5.1.7 on 2025-04-11 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=100)),
                ('prenom_client', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro doit contenir 10 chiffres', regex='^[0-9]{10}$')])),
                ('email_client', models.EmailField(max_length=100)),
            ],
        ),
    ]
