# Generated by Django 5.1.7 on 2025-04-11 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_produit_prix_unitaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('mode_paiement', models.CharField(choices=[('cheque', 'Chèque'), ('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('virement', 'Virement bancaire')], max_length=20)),
                ('date_paiement', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='my_app.commande')),
            ],
        ),
    ]
