# Generated by Django 5.1.7 on 2025-04-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_maladie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinaire',
            fields=[
                ('id_veterinaire', models.AutoField(primary_key=True, serialize=False)),
                ('nom_veterinaire', models.CharField(max_length=50)),
                ('prenom_veterinaire', models.CharField(max_length=20)),
                ('telephone_veterinaire', models.CharField(max_length=20)),
                ('adresse_veterinaire', models.CharField(max_length=100)),
            ],
        ),
    ]
