# Generated by Django 5.1.7 on 2025-04-15 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_veterinaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccin',
            fields=[
                ('id_vaccin', models.AutoField(primary_key=True, serialize=False)),
                ('nom_vaccin', models.CharField(max_length=50)),
                ('description_vaccin', models.TextField()),
                ('date_vaccin', models.DateField()),
                ('id_individu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='my_app.individu')),
                ('id_veterinaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='my_app.veterinaire')),
            ],
        ),
    ]
