# Generated by Django 5.1.7 on 2025-04-15 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_traitement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reproduction',
            fields=[
                ('id_reproduction', models.AutoField(primary_key=True, serialize=False)),
                ('date_saillie', models.DateField()),
                ('date_diagnostic', models.DateField()),
                ('date_prevue', models.DateField()),
                ('date_naissance', models.DateField()),
                ('etat_veau', models.CharField(choices=[('Bon sante', 'Bon état'), ('Malade', 'Malade'), ('Mort-ne', 'Mort-né')], max_length=20)),
                ('id_femelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproductions_femelle', to='my_app.individu')),
                ('id_male', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproductions_male', to='my_app.individu')),
                ('id_veterinaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproductions', to='my_app.veterinaire')),
            ],
        ),
    ]
