# Generated by Django 5.1.7 on 2025-04-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_alter_login_role_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Utilisateur standard'), ('admin', 'Administrateur'), ('gestion_animaux', 'Gestionnaire des animaux'), ('gestion_alimentation', 'Responsable alimentation'), ('gestion_sanitaire', 'Vétérinaire'), ('gestion_production', 'Technicien de production'), ('gestion_ventes', 'Responsable commercial')], default='user', max_length=50),
        ),
    ]
