# Generated by Django 5.1.7 on 2025-04-30 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_alter_customuser_options_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeDetail',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandesdetail', to='my_app.client')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
