# Generated by Django 5.1.7 on 2025-05-01 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_commandedetail_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id_ligne', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='my_app.commandedetail')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'ordering': ['-created_at'],
            },
        ),
    ]
