# Generated by Django 5.1.7 on 2025-05-02 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_alter_lignecommande_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='id_commande',
        ),
        migrations.AddField(
            model_name='paiement',
            name='id_commandeDetail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='my_app.commandedetail'),
            preserve_default=False,
        ),
    ]
