# Generated by Django 5.1.7 on 2025-05-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_remove_paiement_id_commande_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='montant',
        ),
    ]
